import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { formatCurrency, formatPercent, statusTone } from "@/lib/credit";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BrainCircuit, CalendarDays, CreditCard, Gauge, IndianRupee, Loader2, RefreshCw, Sparkles, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";

const pieColors = ["#0ea5e9", "#e2e8f0"];

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const profile = trpc.profile.get.useQuery();
  const history = trpc.profile.history.useQuery();
  const advisor = trpc.advisor.analyze.useMutation({ onSuccess: result => { setAdvice(result); toast.success("Your tailored plan is ready"); }, onError: error => toast.error(error.message || "Could not generate advice") });
  const [advice, setAdvice] = useState<{ summary: string; steps: string[]; riskFlags: string[] } | null>(null);
  const current = profile.data;

  useEffect(() => { if (!profile.isLoading && !current) setLocation("/onboarding"); }, [current, profile.isLoading, setLocation]);

  const lineData = useMemo(() => (history.data?.records || []).map(record => ({ date: new Date(record.recordedAt).toLocaleDateString("en-IN", { month: "short", day: "numeric" }), score: record.creditScore })), [history.data]);
  const utilization = current ? Math.min(Math.max(Number(current.utilizationRatio), 0), 1) : 0;
  const pieData = [{ name: "Used", value: utilization }, { name: "Available", value: Math.max(1 - utilization, 0) }];
  const delta = history.data?.delta ?? null;

  if (profile.isLoading || !current) return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="h-8 w-56 animate-pulse rounded-lg bg-slate-200" /><div className="mt-8 grid gap-5 md:grid-cols-3"><div className="h-48 animate-pulse rounded-3xl bg-white" /><div className="h-48 animate-pulse rounded-3xl bg-white" /><div className="h-48 animate-pulse rounded-3xl bg-white" /></div></div></DashboardLayout>;

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-sky-700">Your credit snapshot</p><h1 className="font-display text-3xl font-semibold tracking-tight text-slate-950 md:text-4xl">Good morning, {current ? "let’s make progress" : ""}.</h1><p className="mt-2 text-slate-500">A clear read on what is helping your score — and what to do next.</p></div><Button onClick={() => setLocation("/profile")} variant="outline" className="w-fit rounded-full border-slate-300 bg-white font-semibold text-slate-700"><RefreshCw className="mr-2 h-4 w-4" /> Update numbers</Button></div>

    <div className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]">
      <div className="relative overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-xl shadow-slate-950/10 md:p-8"><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full bg-sky-500/20 blur-3xl" /><div className="relative flex flex-col gap-8 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-400">Current CIBIL score</p><div className="mt-3 flex items-end gap-3"><span className="font-display text-7xl font-semibold leading-none tracking-[-0.06em]">{current.creditScore}</span><span className={`mb-2 rounded-full border px-3 py-1 text-xs font-bold ${statusTone(current.healthStatus)}`}>{current.healthStatus}</span></div><div className="mt-5 flex items-center gap-2 text-sm">{delta !== null && delta >= 0 ? <TrendingUp className="h-4 w-4 text-emerald-300" /> : <TrendingDown className="h-4 w-4 text-amber-300" />}<span className={delta !== null && delta >= 0 ? "text-emerald-200" : "text-amber-200"}>{delta === null ? "First score recorded" : `${delta >= 0 ? "+" : ""}${delta} points since last update`}</span></div></div><div className="flex h-36 w-36 shrink-0 items-center justify-center rounded-full" style={{ background: "conic-gradient(#34d399 0 82%, rgba(255,255,255,0.12) 82% 100%)" }}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-slate-950"><span className="text-xs font-semibold text-slate-400">Range</span><span className="mt-1 font-display text-lg font-semibold">300 — 900</span></div></div></div></div>
      <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">Credit utilisation</p><p className="mt-2 font-display text-4xl font-semibold text-slate-950">{formatPercent(current.utilizationRatio)}</p><p className="mt-1 text-xs text-slate-400">Keep this below 30% where possible</p></div><div className="h-28 w-28"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" innerRadius={34} outerRadius={49} paddingAngle={3} strokeWidth={0}>{pieData.map((_, index) => <Cell key={index} fill={pieColors[index]} />)}</Pie></PieChart></ResponsiveContainer></div></div><div className="mt-5 flex justify-between border-t border-slate-100 pt-4 text-xs"><span className="font-semibold text-slate-600">{formatCurrency(current.outstandingDebt)} used</span><span className="text-slate-400">of {formatCurrency(current.creditLimit)} limit</span></div></div>
    </div>

    <div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={Gauge} label="Debt-to-income" value={formatPercent(current.dtiRatio)} helper="Monthly debt / income" tone="sky" /><MetricCard icon={WalletCards} label="Missed payments" value={String(current.missedPayments)} helper="Reported in the last year" tone="amber" /><MetricCard icon={CreditCard} label="Active loans" value={String(current.activeLoans)} helper="Across your accounts" tone="emerald" /></div>

    <div className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="mb-6 flex items-start justify-between"><div><p className="text-sm text-slate-500">Progress over time</p><h2 className="mt-1 font-display text-xl font-semibold text-slate-950">Score history</h2></div><div className="rounded-xl bg-slate-50 p-2 text-slate-400"><CalendarDays className="h-4 w-4" /></div></div>{lineData.length > 0 ? <div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={lineData} margin={{ top: 10, right: 8, left: -24, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} /><YAxis domain={[300, 900]} axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e2e8f0", boxShadow: "0 8px 30px rgba(15,23,42,0.08)" }} /><Line type="monotone" dataKey="score" stroke="#0284c7" strokeWidth={3} dot={{ r: 4, fill: "#0284c7", stroke: "#fff", strokeWidth: 2 }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></div> : <div className="flex h-64 items-center justify-center rounded-2xl bg-slate-50 text-sm text-slate-500">Your first score point will appear here.</div>}</div>
      <div className="rounded-[2rem] border border-sky-100 bg-sky-50/70 p-6 shadow-sm md:p-8"><div className="flex items-center gap-2 text-sky-700"><BrainCircuit className="h-5 w-5" /><p className="text-sm font-bold uppercase tracking-[0.12em]">AI advisor</p></div><h2 className="mt-4 font-display text-2xl font-semibold text-slate-950">Turn your snapshot into a plan.</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Get a plain-language readout and five practical next steps tailored to your current numbers.</p><Button onClick={() => advisor.mutate()} disabled={advisor.isPending} className="mt-6 w-full rounded-xl bg-sky-700 font-semibold text-white hover:bg-sky-800">{advisor.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}{advisor.isPending ? "Reviewing your numbers…" : "Get my AI advice"}</Button><p className="mt-3 text-center text-[11px] text-slate-400">Educational guidance, not a promise of score movement.</p></div>
    </div>

    {advice && <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2 text-emerald-700"><Sparkles className="h-4 w-4" /><p className="text-xs font-bold uppercase tracking-[0.16em]">Your tailored plan</p></div><p className="mt-3 max-w-3xl text-lg leading-relaxed text-slate-700">{advice.summary}</p></div><Button variant="outline" onClick={() => setLocation("/recommendations")} className="w-fit shrink-0 rounded-full border-slate-300 font-semibold">View history <ArrowUpRight className="ml-2 h-4 w-4" /></Button></div><div className="mt-7 grid gap-3 md:grid-cols-5">{advice.steps.map((step, index) => <div key={step} className="rounded-2xl bg-slate-50 p-4"><span className="font-display text-2xl font-semibold text-sky-700">0{index + 1}</span><p className="mt-3 text-sm leading-relaxed text-slate-600">{step}</p></div>)}</div>{advice.riskFlags.length > 0 && <div className="mt-6 flex flex-wrap gap-2">{advice.riskFlags.map(flag => <span key={flag} className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-800">{flag}</span>)}</div>}</div>}
  </div></DashboardLayout>;
}

function MetricCard({ icon: Icon, label, value, helper, tone }: { icon: typeof Gauge; label: string; value: string; helper: string; tone: "sky" | "amber" | "emerald" }) {
  const tones = { sky: "bg-sky-50 text-sky-700", amber: "bg-amber-50 text-amber-700", emerald: "bg-emerald-50 text-emerald-700" };
  return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mb-5 flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}><Icon className="h-5 w-5" /></div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-display text-3xl font-semibold text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{helper}</p></div>;
}
